# cmake -DCMAKE_BUILD_PLATFORM=UBUNTU64 -DCMAKE_BUILD_TYPE=DEBUG -DSELF_BUILD=on ..
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(BaseEvent)
set_property(GLOBAL PROPERTY USE_FOLDERS On)

MESSAGE(STATUS "01*********************************************************")
INCLUDE(cmake/global_environment_settings.cmake)
IF(WIN32)
	IF(MSVC12)
		INCLUDE(cmake/win_vs2013_environment_settings.cmake)
	ELSEIF(MSVC14)
		INCLUDE(cmake/win_vs2017_environment_settings.cmake)
	ELSEIF (MSVC90)
		INCLUDE(cmake/win_vs2008_environment_settings.cmake)
	ENDIF()
ELSEIF(UNIX)
	#ADD_COMPILE_OPTIONS(-fpermissive)
	IF(CMAKE_BUILD_PLATFORM MATCHES ARM3730)
    MESSAGE("CMAKE_BUILD_PLATFORM MATCHES ARM3730")
		INCLUDE(cmake/arm3730_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES HISIV300)
    MESSAGE("CMAKE_BUILD_PLATFORM MATCHES HISIV300")
		INCLUDE(cmake/hisi_v300_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES HISIV500)
    MESSAGE("CMAKE_BUILD_PLATFORM MATCHES HISIV500")
		INCLUDE(cmake/hisi_v500_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES LITEOS)
    MESSAGE("CMAKE_BUILD_PLATFORM MATCHES LITEOS")
		INCLUDE(cmake/himix100_liteos_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES ARM8127)
    MESSAGE("CMAKE_BUILD_PLATFORM MATCHES ARM8127")
		INCLUDE(cmake/arm8127_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES ARM6446)
    MESSAGE("CMAKE_BUILD_PLATFORM MATCHES ARM6446")
		INCLUDE(cmake/arm6446_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES UBUNTU64)
    MESSAGE("CMAKE_BUILD_PLATFORM MATCHES UBUNTU64")
		INCLUDE(cmake/ubuntu64_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES HIMIX100)
	MESSAGE("CMAKE_BUILD_PLATFORM MATCHES HIMIX100")
		INCLUDE(cmake/himix100_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES HIMIX200S1L)
	MESSAGE("CMAKE_BUILD_PLATFORM MATCHES HIMIX200_S1L")
		INCLUDE(cmake/himix200_S1L_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES HIMIX200)
	MESSAGE("CMAKE_BUILD_PLATFORM MATCHES HIMIX200")
		INCLUDE(cmake/himix200_environment_settings.cmake)
	ELSEIF(CMAKE_BUILD_PLATFORM MATCHES MSTAR)
	MESSAGE("CMAKE_BUILD_PLATFORM MATCHES MSTAR")
		INCLUDE(cmake/mstar_environment_settings.cmake)
	ENDIF()
ENDIF()

MESSAGE(STATUS "02*********************************************************")
INCLUDE_DIRECTORIES(${VZPROJECT_INCLUDE_DIR})
LINK_DIRECTORIES(${VZPROJECT_LIBRARY_DIR})

# add_compile_options(-fpermissive)
include_regular_expression("^([^p]|p[^r]|pr[^e]|pre[^c]|prec[^o]|preco[^m]|precom[^p])")

ADD_SUBDIRECTORY(src/lib/os)
ADD_SUBDIRECTORY(src/lib/eventservice)
ADD_SUBDIRECTORY(src/lib/filecache)
ADD_SUBDIRECTORY(src/lib/app)
ADD_SUBDIRECTORY(src/lib/log)
ADD_SUBDIRECTORY(src/lib/config)

# Third part
ADD_SUBDIRECTORY(src/third_part/astl)
ADD_SUBDIRECTORY(src/third_part/json)
ADD_SUBDIRECTORY(src/third_part/encode)
ADD_SUBDIRECTORY(src/third_part/tinyxml2)
ADD_SUBDIRECTORY(src/third_part/sqlite3)

# TEST
IF(SELF_BUILD MATCHES on)
# ADD_SUBDIRECTORY(test/libevent_test)
# ADD_SUBDIRECTORY(src/test/thead_test)
# ADD_SUBDIRECTORY(src/test/tcpserver)
# ADD_SUBDIRECTORY(src/test/ns_tcpserver)
# ADD_SUBDIRECTORY(src/test/tcpclient)
# ADD_SUBDIRECTORY(src/test/httpserver)
# ADD_SUBDIRECTORY(src/test/select_test)
# ADD_SUBDIRECTORY(src/test/smart_test)
# ADD_SUBDIRECTORY(src/test/multiple_http_server)
# ADD_SUBDIRECTORY(src/test/udpserver)
# ADD_SUBDIRECTORY(src/test/udpclient)
# ADD_SUBDIRECTORY(src/test/multicast_server)
# ADD_SUBDIRECTORY(src/test/packet_client)
# ADD_SUBDIRECTORY(src/test/packet_server)
# ADD_SUBDIRECTORY(src/test/dptest)
# ADD_SUBDIRECTORY(src/test/membuffertest)
# ADD_SUBDIRECTORY(src/test/signalevent_test)
# ADD_SUBDIRECTORY(src/test/appstarup)
# ADD_SUBDIRECTORY(src/test/filecache_test)
# ADD_SUBDIRECTORY(src/test/cachenetclient_test)
# ADD_SUBDIRECTORY(src/test/cachenetserver_test)
# ADD_SUBDIRECTORY(src/test/config_test)
# ADD_SUBDIRECTORY(src/test/encode_test)
# ADD_SUBDIRECTORY(src/test/watchdog_test)
# ADD_SUBDIRECTORY(src/test/log_test1)
# #ADD_SUBDIRECTORY(src/test/log_test2)
# ADD_SUBDIRECTORY(src/test/log_test3)
# ADD_SUBDIRECTORY(src/test/dpserver)
# ADD_SUBDIRECTORY(src/test/dpclient)

#TOOLS
#ADD_SUBDIRECTORY(src/tools/logparser)
#ADD_SUBDIRECTORY(src/tools/logserver)
ENDIF()

ADD_SUBDIRECTORY(cmake)
MESSAGE(STATUS "06*********************************************************")
