include(CMakeForceCompiler)
SET(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
SET(CMAKE_SYSTEM_VERSION 1)

SET(CROSS_TOOL_PREFIX arm-hisiv500-linux-)
SET(CMAKE_C_COMPILER   ${CROSS_TOOL_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER ${CROSS_TOOL_PREFIX}g++)
SET(CMAKE_STRIP ${CROSS_TOOL_PREFIX}strip)
SET(CMAKE_AR ${CROSS_TOOL_PREFIX}ar)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(PLATFORM_NAME hisiv500)
SET(FTP_DIR "${PROJECT_SOURCE_DIR}/ftp/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")

SET(VZPROJECT_INCLUDE_DIR
        ${PROJECT_SOURCE_DIR}/src/lib
        ${PROJECT_SOURCE_DIR}/src/third_part
        ${PROJECT_SOURCE_DIR}/src/third_part/boost
        )

SET(VZPROJECT_LIBRARY_DIR
	)

MESSAGE(STATUS "       Add LIBRARY PATH AND NAME")
IF (CMAKE_BUILD_TYPE MATCHES Debug)
    MESSAGE(STATUS "       Debug Mode")
    SET(VZPROJECT_LIBRARY_DIR
		)
    SET(VZPROJECT_LINK_LIB
		-Wl,-rpath=.
		pthread
		rt
		dl
		)
    SET(DO_FLAG -DO0 -g)
    SET(O_FLAG -O0)
ELSEIF (CMAKE_BUILD_TYPE MATCHES Release)
    MESSAGE(STATUS "       RELEASE MODE")
    MESSAGE(STATUS "       UNIX")
    SET(VZPROJECT_LIBRARY_DIR
		)
    SET(VZPROJECT_LINK_LIB
		-Wl,-rpath=.
		pthread
		rt
		dl
		)
    SET(DO_FLAG -DO2)
    SET(O_FLAG -O2)
ENDIF ()

# SDK defined C&C++ flags
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${O_FLAG} -std=c99 -Wno-deprecated-declarations")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${O_FLAG} -std=c++11 -Wno-deprecated-declarations")

MESSAGE(STATUS "SETP 4 : ADD CODE SOURCE")

ADD_DEFINITIONS(
		# EventBase macros define
		${DO_FLAG}
		-D_LINUX
		-DPOSIX
		-fpermissive
)

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/lib/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/lib/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")

SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR}/bin/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR}/lib/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${PROJECT_SOURCE_DIR}/lib/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")

# With Release properties
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR}/bin/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR}/lib/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${PROJECT_SOURCE_DIR}/lib/${PLATFORM_NAME}/${CMAKE_BUILD_TYPE}")
